baknetworks/core/views.py
####################
###CORE VIEWS.PY####
####################

from baknetworks import APP_ROOT
from flask import render_template, Blueprint, send_file, redirect
from flask_login import login_required, current_user
import os

#Configure blueprint for core routes
core = Blueprint('core',__name__)

#Index Routing
@core.route('/')
def index():
    return render_template('index.html')

#DevDiary Routing
@core.route('/devdiary')
def devdiary():
    return render_template('devdiary.html')

#Contact Routing
@core.route('/contact')
def contact():
    return render_template('contact.html')

#Privacy Page Routing
@core.route('/privacy')
def privacy():
    return render_template('privacy.html')

#Database Routeing
@core.route('/database')
@login_required
def send_database():
    #Checks logged in user, and permits download of database if current user is admin.
    if current_user.email == "benjamin.a.kavanagh@gmail.com":
        filename = 'data.sqlite'
        filepath = os.path.join(APP_ROOT, filename)
        return send_file(filepath, as_attachment=True)
    #Else re-routes to index 
    else:
        return redirect (url_for('core.index'))

baknetworks/networks/views.py
#######################
###NETWORKS VIEWS.PY###
#######################

from flask import render_template, Blueprint, redirect, url_for
from flask_login import current_user
from baknetworks.comment.forms import CommentForm 
from baknetworks.models import Comment
from baknetworks.networks.forms import RNNForm, CNNForm
from baknetworks import db, APP_ROOT
from baknetworks.networks.predictions import prepare_network, generate_text, detect_covid
from werkzeug.utils import secure_filename
import numpy as np
import os
import gc

#Set up Blueprint for Networks Views
networks = Blueprint('networks',__name__)

#RNN Route
@networks.route('/rnn/')
def rnn_root():
    #Run Garbage Collector
    gc.collect()
    return render_template('rnn.html')

##################################################
##################SHAKESBOT#######################
##################################################

#Shakesbot Route
@networks.route('/rnn/shakesbot', methods=['GET', 'POST'])
def rnn_shake():

    #Create an RNN Form instance
    rnnform = RNNForm(prefix='a')

    #Creete a Comment Form instance
    commentform = CommentForm(prefix='b')

    #Set default rnnoutput to False
    rnnoutput=False

    #If Comment form has been submitted
    if commentform.submit.data and commentform.validate():
        
        #Extract Comment data from form
        savecomment = Comment(text=commentform.text.data,
                            user_id=current_user.id,
                            page='rnn_shake')

        #Save and Commit Comment data to Database       
        db.session.add(savecomment)
        db.session.commit()
        return redirect(url_for('networks.rnn_shake'))

    #If RNN form has been submitted 
    if rnnform.submitrnn.data and rnnform.validate():

        #Extract RNN Form data
        start_seed = rnnform.textrnn.data
        temp = rnnform.temprnn.data/100
        filename='shakespeare'

        #Pass Form Data to Shakesbot text generation
        rnnoutput = generate_text(start_seed, temp, filename)
        
        #Filter comment data for this page
        commentquery = Comment.query.filter_by(page='rnn_shake').all()

        #Return Relevant Information to page
        return render_template('rnn_shake.html', commentform=commentform, commentquery=commentquery, rnnform=rnnform, rnnoutput=rnnoutput)
    
    #Filter comment data for this page
    commentquery = Comment.query.filter_by(page='rnn_shake').all() 
    #Return Relevant Information to page
    return render_template('rnn_shake.html', commentform=commentform, commentquery=commentquery, rnnform=rnnform)

###################################################
##################TOLSTOYBOT#######################
###################################################

#Tolstoy Route
@networks.route('/rnn/tolstoybot', methods=['GET', 'POST'])
def rnn_tolstoy():

    #Create RNN Form Instance
    rnnform = RNNForm(prefix='a')

    #Create Comment Form Instance
    commentform = CommentForm(prefix='b')

    #Set default rnnoutput to False
    rnnoutput=False

    #If Comment form has been submitted
    if commentform.submit.data and commentform.validate():

        #Extract Comment data from form
        savecomment = Comment(text=commentform.text.data,
                            user_id=current_user.id,
                            page='rnn_tolstoy')    

        #Save and Commit Comment data to Database    
        db.session.add(savecomment)
        db.session.commit()
        return redirect(url_for('networks.rnn_tolstoy'))

    #If RNN form has been submitted 
    if rnnform.submitrnn.data and rnnform.validate():

        #Extract RNN Form data
        start_seed = rnnform.textrnn.data
        temp = rnnform.temprnn.data/100
        filename='tolstoybot'
        
        #Pass Form Data to Tolstoybot text generation
        rnnoutput = generate_text(start_seed, temp, filename)
        
        #Filter comment data for this page
        commentquery = Comment.query.filter_by(page='rnn_tolstoy').all()
        #Return Relevant Information to page
        return render_template('rnn_tolstoy.html', commentform=commentform, commentquery=commentquery, rnnform=rnnform, rnnoutput=rnnoutput)
    
    #Filter comment data for this page
    commentquery = Comment.query.filter_by(page='rnn_tolstoy').all()
    #Return Relevant Information to page
    return render_template('rnn_tolstoy.html', commentform=commentform, commentquery=commentquery, rnnform=rnnform)

#CNN Route
@networks.route('/cnn')
def cnn():
    #Run Garbage Collector
    gc.collect()
    return render_template('cnn.html')

##############################################
##################COVID#######################
##############################################

#CNN Route
@networks.route('/cnn/covid', methods=['GET', 'POST'])
def cnn_covid():
    
    #Create CNN Form instance
    cnnform = CNNForm(prefix='a')

    #Create Comment Form
    commentform = CommentForm(prefix='b')

    #If Comment form has been submitted
    if commentform.validate_on_submit():

        #Extract Comment data from form
        savecomment = Comment(text=commentform.text.data,
                            user_id=current_user.id,
                            page='cnn_covid')

        #Save and Commit Comment data to Database  
        db.session.add(savecomment)
        db.session.commit()
        return redirect(url_for('networks.cnn_covid'))

    #If CNN form has been submitted 
    if cnnform.submitcnn.data and cnnform.validate():
    
        #Obtain Filename
        filename = secure_filename(cnnform.filecnn.data.filename)
        
        #Set Filepath
        filepath = os.path.join(APP_ROOT, 'static', filename)

        #Save file
        cnnform.filecnn.data.save(filepath)
        
        #Run Model, obtain prediction
        cnnoutput = detect_covid(filepath)
        
        #Set text based output Classification based on prediction
        if cnnoutput[0][0] < 0.5:
            cnnoutput = "The model has predicted this is a COVID 19 X Ray"
        else:
            cnnoutput = "The model has predicted this is a NORMAL X Ray"  

        #Remove File
        os.remove(filepath)
                       
        #Filter comment data for this page
        commentquery = Comment.query.filter_by(page='cnn_covid').all()

        #Return Relevant Information to page
        return render_template('cnn_covid.html', commentform=commentform, commentquery=commentquery, cnnform=cnnform, cnnoutput=cnnoutput)
    
    #Filter comment data for this page
    commentquery = Comment.query.filter_by(page='cnn_covid').all()

    #Return Relevant Information to page
    return render_template('cnn_covid.html', commentform=commentform, commentquery=commentquery, cnnform=cnnform)


#GAN Route
@networks.route('/gan', methods=['GET', 'POST'])
def gan():
    gc.collect()
    #Create Comment Form Instance
    commentform = CommentForm(prefix='a')

    #If Comment form has been submitted
    if commentform.validate_on_submit():

        #Extract Comment data from form
        savecomment = Comment(text=commentform.text.data,
                            user_id=current_user.id,
                            page='gan')   

        #Save and Commit Comment data to Database  
        db.session.add(savecomment)
        db.session.commit()
        return redirect(url_for('networks.gan'))

    #Filter comment data for this page
    commentquery = Comment.query.filter_by(page='gan').all()

    #Return Relevant Information to page
    return render_template('gan.html', commentform=commentform, commentquery=commentquery)

baknetworks/users/views.py
####################
###USERS VIEWS.PY###
####################

from flask import  redirect, url_for, Blueprint
from flask_login import login_required, logout_user, current_user

# Set up users blueprint
users = Blueprint('users',__name__)

#Log in route
@users.route('/google')
def login():
    if not current_user.is_authenticated:
        return redirect(url_for('google.login'))
    return redirect(url_for('core.index'))

#Log out route
@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('core.index'))

baknetworks/templates/base.html
<!doctype html>
<html lang="en">

  <!-- Head -->
  <head>
    <title>BAK Networks</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Google Verification -->
    <meta name="google-site-verification" content="6O2WIgw3hUn1-DG7f09Ri3P907S48ruuQ0TbGqHgPFc" />

    <!-- Bootstrap imports -->  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <!-- MY CSS-->
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css')}}"/>
  
    <!-- Google Fonts-->
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300&display=swap" rel="stylesheet"> 

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='favicon/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon/favicon-16x16.png')}}">
    <link rel="manifest" href="{{ url_for('static', filename='favicon/site.webmanifest')}}">
    <link rel="mask-icon" href="{{ url_for('static', filename='favicon/safari-pinned-tab.svg')}}" color='#5bbad5'>
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    
  </head>
  
  <!--body -->
  <body>

    <!--Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <!-- LEFT -->
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            
            <ul class="navbar-nav mr-auto">

                <!-- Dev Diary  -->
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('core.devdiary')}}">Dev Diary</a>
                </li>

                <!-- Neural Networks -->

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Neural Networks
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{url_for('networks.rnn_root')}}">Recurrent</a>
                        
                        <div class="dropdown-divider"></div>
                        
                        <a class="dropdown-item" href="{{url_for('networks.gan')}}">Generative Adversarial</a>
                                                                                
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{url_for('networks.cnn')}}">Convolutional</a>

                    </div>
                </li>

                <!-- Contact -->
                
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('core.contact')}}">Contact</a>
                </li>
            </ul>
        </div>

        <!-- CENTER -->

        <div class="mx-auto order-0">
            <a class="navbar-brand mx-auto" href="{{url_for('core.index')}}">A Portfolio by Benjamin Kavanagh</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>

        <!-- RIGHT --> 
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">

                <!-- Database -->
            
                {%if current_user.is_authenticated %}

                {%if current_user.email == "benjamin.a.kavanagh@gmail.com" %}
                
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('core.send_database')}}"><button class="btn btn-sm btn-outline-secondary">Database</button></a>
                </li>

                {%endif%}

                <!-- User Image -->

                <li class="nav-item">
                    <a class="nav-link" ><img class="logo-image img-fluid rounded-circle" src="{{current_user.picture}}"/></a>
                </li>

                <!-- Log Out -->

                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.logout')}}"><button class="btn btn-sm btn-outline-secondary">Log Out</button></a>
                </li>
                    
                {%else%}    
                
                <!-- Log in -->
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('users.login')}}"><button class="btn btn-sm btn-outline-secondary">Log In</button></a>
                </li>

                {%endif%}

            </ul>
        </div>
    </nav>
 

    {% block content %}
    
    {% endblock content %}

     
    
  </body>
</html>

baknetworks/templates/cnn.html
{% extends "base.html" %}

{% block content %}

<!-- Jumbotron -->

<div class="jumbotron jumbotron-fluid">
    <div class="container-fluid">
        <div class="d-flex justify-content-center text-center">
            <h1 class="display-1">Convolutional Neural Network</h1>
        </div>       

    </div>
</div>


<div class="container pt-4 bg-dark text-white text-center">

    <span class="display-2"> What's a CNN? </span><br>
    A CNN is a class of networks commonly used for analyzing image data! <br>
    <hr class="my-2">
    Convolutional Neural Networks contain 3-dimensional layers (width, height, and depth),<br>
    and use filters to perform 'feature extraction' on images, ultimately assigning a probability<br>
    to the possible classifications being trained. 
    
    <hr class="my-2">

    Click below to choose a CNN to interact with!

</div>


<!-- Choices -->


<div class="container pt-4">
    <div class="row d-flex p-2"> 
        <div class="col-sm-3"></div>  

            <div class="col-sm-6">
                <div class="card">
                    <div class="card-header text-center">
                        COVIDXNet
                    </div>
                    <div class="card-body text-center">
                    <h5 class="card-title text-center">A Deep Convolutional Neural Network</h5>
                    <p class="card-text text-center">Classify X-Ray images as either COVID or Normal</p>
                    <a href="{{url_for('networks.cnn_covid')}}" class="btn btn-secondary text-center">COVIDXNet</a>
                    </div>
                </div>
            </div>
        
        <div class="col-sm-3"></div>  

    </div>
</div>





{% endblock content %}

baknetworks/templates/cnn_covid.html
{% extends "base.html" %}

{% block content %}

<!-- Jumbotron -->

<div class="jumbotron jumbotron-fluid">
    <div class="container-fluid">
        <div class="d-flex justify-content-center text-center">
            <h1 class="display-1">COVIDXNet</h1>
        </div>
        
        <hr class="my-2">
        <div class="d-flex justify-content-center text-center">
            <p><a href="https://github.com/BAK2K3/COVIDXNet" target="_blank">A CNN for COVID detection in chest X Rays</a></p>
        </div>
    </div>
</div>


<!-- RNN User input Form-->

<div class="container pt-4 bg-dark text-white text-center">

    <span class="h2"> Upload a chest X-Ray image!</span><br>
    You can download plenty of pictures from <a href=https://github.com/ieee8023/covid-chestxray-dataset/tree/master/images target="_blank">this public github</a>.<br>
    Alternativelty, there are other <a href=https://www.researchgate.net/post/updated_list_Last_updated_June_25th_2020_of_Coronavirus_Covid-19_dataset_and_other_Research_Resources target="_blank">Open Source repositories</a> to obtain samples.<br>
    <em>The model will then prodict whether the X-Ray contains COVID symptoms.</em><br>
    <strong>DISCLAIMER: THIS IS A LEARNING PROJECT, NOT TO BE USED FOR RELIABLE MEDICAL ADVICE OR DIAGNOSIS. <br>THIS HAS NOT BEEN SUBJECT TO GOVERNMENT OR MEDICAL TESTING, AND SHOULD NOT BE USED FOR RELIABLE SELF DIAGNOSIS. </strong>
    <hr class="my-2">
    <form method="POST" enctype="multipart/form-data">
        <div class='container pt-4'>
            <div class="form-group">
                {{cnnform.hidden_tag()}}
                {{cnnform.filecnn}}
                {{cnnform.submitcnn(class="btn btn-secondary mb-2")}}   
            </div>
        </div>        
    </form>

    {% if cnnoutput %}

    <hr class="my-2">
    
    <p class="h3">{{cnnoutput}}</p>
      
    <br>
    {% endif %}

    </div>
    

<!-- Comments -->

<div class="container fixed-bottom">
    <div id="accordion">
        <div class="card">
          <div class="card text-center" id="headingOne">
                <button class="btn btn-secondary" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    <h2>COVIDXNet Comments</h2>
                </button>
          </div>
        
            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                    
                    {%if current_user.is_authenticated %}
                    <!-- Comment Form -->
                    <form method="POST">
                        <div class=form-group>
                        <div class="row">
                            {{commentform.hidden_tag()}}
                            <div class='col text-dark text-center'>
                            {{commentform.text.label}}
                            </div>
                            <div class='col text-center'>
                                {{commentform.submit(class="btn btn-secondary mb-2")}}
                            </div>
                        </div>
                        <div class="row">
                            <div class='col mb-2'>
                            {{commentform.text(class="form-control border border-dark")}}
                            </div>
                        </div>
                    </form>

                    {%else%}

                    <div class='col text-dark text-center'>
                        <p> Please Log in to leave a comment! </p>
                    </div>

                    {%endif%}


                    <!-- Scrollable Table -->
                    <div class="table-wrapper-scroll-y my-custom-scrollbar">
                        <table class="table table-bordered table-dark mb-0">
                            <thead>
                                <tr>
                                    <th scope="col">No </th>
                                    <th scope="col">Author</th>
                                    <th scope="col">Date</th>
                                    <!-- <th scope='col'>Title</th> -->
                                    <th scope='col' colspan="4">Comment</th>                                                          
                                </tr>
                            </thead>
                
                            <tbody>
                            
                                {% for comment in commentquery %}
                                <tr>
                                    <th scope="row">{{loop.index}}</th>
                                    <td>{{comment.users.name.split(' ')[0]}}</td>
                                    <td>{{comment.date.date()}}</td>
                                    <th colspan="4">{{comment.text}}</th>
                                </tr>
                                {%endfor%}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




{% endblock content %}

baknetworks/templates/contact.html
{% extends "base.html" %}

{% block content %}

<!-- Jumbotron -->

<div class="jumbotron jumbotron-fluid">
    <div class="container-fluid">
        <div class="d-flex justify-content-center text-center">
            <h1 class="display-1">Contact</h1>
        </div>
    </div>
</div>


<!-- Contact Me Box -->

<div class='d-flex justify-content-center'>
    <div class="card text-white bg-secondary mb-3 text-center" style="max-width: 50%;">
        <div class="card-header">Want to get in touch?</div>
        <div class="card-body">
            <p class="card-text">Visit one of the network pages to leave a comment, 
            otherwise you can email me directly at benjamin.a.kavanagh@gmail.com.</p>
        </div>
    </div>
</div>

{% endblock content %}

baknetworks/templates/gan.html
{% extends "base.html" %}

{% block content %}

<!-- Jumbotron -->

<div class="jumbotron jumbotron-fluid">
    <div class="container-fluid">
        <div class="d-flex justify-content-center text-center">
            <h1 class="display-1">Generative Adverserial Network</h1>
        </div>
    </div>
</div>

<div class="container pt-4 bg-dark text-white text-center">

    <span class="display-2"> Under Construction! </span><br>
    <!-- <span class="display-2"> What's a GAN? </span><br>
    Generative Adverserial Networks use two Neural Networks against each other! <br>
    <hr class="my-2">
    For this GAN, one network is the "detective", which thinks it knows what a real number looks like!<br>
    The other network, the "generator", has learned how to <em>fool</em> the "detective".<br>
    From this, the generator is able to produce randomly generated hand drown numbers!<br>
    
    <hr class="my-2">

    Click below to generate an image via the "generator".<br>
    Then, head over to the Convolutional page to see if our CNN can correctly identify the number!  -->

 

 

</div>






<!-- Comments -->

<div class="container fixed-bottom">
    <div id="accordion">
        <div class="card">
            <div class="card text-center" id="headingOne">
                <button class="btn btn-secondary" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    <h3>GAN Comments</h3>
                </button>
            </div>
            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                    
                    {%if current_user.is_authenticated %}
                    <!-- Comment Form -->
                    <form method="POST">
                        <div class=form-group>
                        <div class="row">
                            {{commentform.hidden_tag()}}
                            <div class='col text-dark text-center'>
                            {{commentform.text.label}}
                            </div>
                            <div class='col text-center'>
                                {{commentform.submit(class="btn btn-secondary mb-2")}}
                            </div>
                        </div>
                        <div class="row">
                            <div class='col mb-2'>
                            {{commentform.text(class="form-control border border-dark")}}
                            </div>
                        </div>
                    </form>

                    {%else%}

                    <div class='col text-dark text-center'>
                        <p> Please Log in to leave a comment! </p>
                    </div>

                    {%endif%}
                              
                    <!-- Scrollable Table -->
                    <div class="table-wrapper-scroll-y my-custom-scrollbar">
                        <table class="table table-bordered table-dark mb-0">
                            <thead>
                                <tr>
                                    <th scope="col">No </th>
                                    <th scope="col">Author</th>
                                    <th scope="col">Date</th>
                                    <!-- <th scope='col'>Title</th> -->
                                    <th scope='col' colspan="4">Comment</th>                                                          
                                </tr>
                            </thead>
                            <tbody>
                            
                                {% for comment in commentquery %}
                                <tr>
                                    <th scope="row">{{loop.index}}</th>
                                    <td>{{comment.users.name}}</td>
                                    <td>{{comment.date.date()}}</td>
                                    <th colspan="4">{{comment.text}}</th>
                                </tr>
                                {%endfor%}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

baknetworks/templates/index.html
{% extends "base.html" %}

{% block content %}


<!-- Welcome Banner -->
<div class="jumbotron jumbotron-fluid">
    <div class="container-fluid">
        <div class="d-flex justify-content-center text-center">
            <h1 class="display-1">Welcome to an online portfolio</h1>
        </div>
    </div>
</div>

<!-- Welcome Text -->

<div class="container bg-light border border-dark rounded">
<hr class="my-2">   
<p>Hi. My name is Benjamin Kavanagh, and I am an aspiring developer. <strong>Thank you</strong> for visiting my portfolio.</p>

<p>This website has been built using Python, HTML, CSS, and (the tiniest bit of) Javascript, and is hosted on Heroku using a single dyno. While its primary intention is to showcase the workings of interactive user interfaced Neural Networks, it also demonstrates full stack development, including:</p>

<p><strong>Back-end:</strong></p>

<ul>
    <li>Web Framework Development using Flask.</li>
    <li>Database Management using SQLAlchemy (SQLite).</li>
    <li>User Authentication through OAuth.</li>
    <li>Web Application Security using HTTPS, SSL, TLS, and SCPs.</li>
    <li>Web Server Gateway Interfacing using GUnicorn. </li>
    <li>Neural Network Deployment using TensorFlow.</li>
    <li>Form control and security using WTForms.</li>
</ul>

<p><Strong>Front End</Strong></p>

<ul>
    <li>Web development through HTML and CSS (utilising Bootstrap) and Javascript.</li>
</ul>
<hr class="my-2">
<p>This project is completely open source, and I encourage you to visit its <a href="https://github.com/BAK2K3/BAKNetwork" target="_blank">repository</a>. All code is maintained, commented, and organised.  Each Neural Network has its own repository, for CLI training and testing, including <a href="https://github.com/BAK2K3/Shakesbot" target="_blank">Shakesbot</a>, <a href="https://github.com/BAK2K3/Tolstoybot" target="_blank">Tolstoybot</a>, and <a href="https://github.com/BAK2K3/COVIDXNet" target="_blank">COVIDXNet.</a></p>

<p>The Dev Log page provides entries which detail the progression and development process of this portfolio, discussing the challenges faced, and how particular decisions were made.</p>

<p>The Neural Network Page showcases some of the Neural Networks I've developed. Currently all deployed Neural Networks are interactive.</p>

<p><strong>It is not a requirement that you log in.</strong> This functionality merely acts as a demonstration of user login handling, OAuth autherisation with a third party, database management, and web security. 
    The website is secured using SSL, TLS, and HTTPS, with an extremely secure custom Security Content Protocol, and no passwords are saved within the server's database. As such, the only benefit to logging in is 
    to leave a comment for other users to see. All primary functionality is available to everyone.<p>

<p>Thank you for taking your time to visit my portfolio, and I hope you appreciate the passion and joy this project has brought to me.</p>
<hr class="my-2">

</div>
{% endblock content %}